create table vme.dat_requests
(
    id                      bigserial,
    state                   varchar(40) not null,
    req_number              integer,
    req_sub_number          integer,
    req_date                timestamp,
    obj_uid                 varchar(40) not null,
    route                   jsonb,
    req_type                varchar(40),
    type_of_work            varchar(255),
    type_machine            varchar(255),
    req_comment             varchar(2000),
    dimensions              jsonb,
    weight_cargo            double precision,
    volume_cargo            double precision,
    amount                  varchar(40),
    count_ts                integer,
    kind_type               varchar(255),
    cnt_trip                integer,
    work_info               varchar(255),
    passenger_info          varchar(255),
    additional_options      jsonb,
    customer                jsonb,
    date_send               timestamp   not null,
    date_receiving          timestamp,
    organization            bigint      not null,
    customer_app            varchar(255),
    date_start              timestamp,
    date_finish             timestamp,
    id_own_customer         integer,
    report_date             timestamp,
    created_by              varchar(255),
    last_modified_by        varchar(255),
    created_at              timestamp   not null,
    updated_at              timestamp,
    status                  varchar(40),
    "model"                 varchar(100),
    mileage                 double precision,
    moto_hour               double precision,
    mo_hour                 double precision,
    shift_count             integer,
    passenger_count         integer,
    mileage_cargo           double precision,
    mass_cargo              double precision,
    feed_date               varchar(40),
    return_date             varchar(40),
    feed_point_date         varchar(40),
    return_point_date       varchar(40),
    idle_mileage            double precision,
    idle_mo_hours           double precision,
    id_transport_contractor integer,
    id_transport_external   integer,
    tops                    jsonb,
    vehicle_id bigint,
    driver_fio varchar(150),
    driver_contact_info varchar(200),
    constraint pk_dat_requests primary key (id)
);
